import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageNotifier extends ChangeNotifier {
  static const String _langKey = 'language_code';
  String _currentLanguage = 'id'; // 'id' or 'en'

  LanguageNotifier() {
    _loadLanguage();
  }

  String get currentLanguage => _currentLanguage;

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString(_langKey) ?? 'id';
    notifyListeners();
  }

  Future<void> changeLanguage(String langCode) async {
    _currentLanguage = langCode;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_langKey, langCode);
  }

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'id': {
      'app_title': 'RuangTenang',
      'welcome': 'Selamat datang kembali',
      'how_feel': 'Bagaimana perasaanmu hari ini?',
      'start_journal': 'Mulai Jurnal Baru',
      'journal_desc': 'Curahkan isi hatimu hari ini agar pikiran lebih tenang.',
      'chat_now': 'Curhat\nSekarang',
      'recent_journal': 'Jurnal Terbaru',
      'see_all': 'Lihat Semua →',
      'stats_mood': 'Statistik Mood',
      'total_journal': 'Total Jurnal',
      'dominant_mood': 'Mood Dominan',
      'relax_session': 'Sesi Relaksasi',
      'profile_title': 'Profil & Pengaturan',
      'app_settings': 'Pengaturan Aplikasi',
      'dark_mode': 'Mode Gelap',
      'notif': 'Notifikasi',
      'lang': 'Bahasa',
      'privacy': 'Privasi & Keamanan',
      'help_info': 'Bantuan & Info',
      'help_center': 'Pusat Bantuan',
      'about_app': 'Tentang Aplikasi',
      'logout': 'Keluar',
      'logout_confirm': 'Yakin ingin keluar?',
      'cancel': 'Batal',
      'edit_profile': 'Edit Profil',
      'save': 'Simpan',
      'health_mental': 'Edukasi Kesehatan Mental',
      'health_desc': 'Pelajari teknik meditasi, manajemen stres, dan lainnya.',
      'edu_center': 'Pusat Edukasi',
      'all_articles': 'Semua Artikel →',
      'tab_home': 'Beranda',
      'tab_journal': 'Jurnal',
      'tab_chat': 'Curhat',
      'tab_profile': 'Profil',
      'dash_no_data': 'Belum ada data mood hari ini',
      'dash_error': 'Gagal memuat data mood',
      'send_test_notif': 'Kirim Notifikasi Tes',
      'privacy_title': 'Privasi & Keamanan',
      'account_security': 'Keamanan Akun',
      'data_encryption': 'Enkripsi Data',
      'data_encryption_desc': 'Semua data curhatan dan mood Anda dienkripsi secara lokal di perangkat Anda.',
      'biometric': 'Keamanan Biometrik',
      'biometric_desc': 'Opsi penguncian aplikasi dengan sidik jari atau wajah akan segera hadir.',
      'data_privacy': 'Privasi Data',
      'anon_data': 'Data Anonim',
      'anon_data_desc': 'Kami tidak membagikan identitas pribadi Anda kepada pihak ketiga mana pun.',
      'delete_data': 'Hapus Semua Data',
      'delete_data_desc': 'Anda dapat menghapus seluruh riwayat jurnal Anda kapan saja melalui pengaturan akun.',
      'legal': 'Legalitas',
      'tos': 'Syarat & Ketentuan',
      'tos_content': '1. Penggunaan Layanan\nDengan menggunakan RuangTenang, Anda setuju untuk menggunakan aplikasi ini untuk tujuan kesehatan mental pribadi dan tidak menyalahgunakan sistem AI kami.\n\n2. Batasan Tanggung Jawab\nLayanan ini adalah asisten pendukung berbasis AI dan bukan pengganti konsultasi medis profesional, psikolog, atau psikiater.\n\n3. Akun Pengguna\nAnda bertanggung jawab menjaga kerahasiaan akun dan data login Anda.',
      'privacy_policy': 'Kebijakan Privasi',
      'privacy_content': '1. Pengumpulan Data\nKami menyimpan teks curhatan dan hasil analisis mood Anda untuk memberikan riwayat perkembangan kesehatan mental Anda.\n\n2. Keamanan Data\nData Anda disimpan dengan enkripsi dan tidak akan dibagikan kepada pihak ketiga tanpa izin Anda.\n\n3. Hak Pengguna\nAnda memiliki hak penuh untuk menghapus seluruh riwayat data Anda kapan saja melalui fitur "Hapus Semua Data" di aplikasi ini.',
      'faq_popular': 'Pertanyaan Populer',
      'contact_us': 'Hubungi Kami',
      'search_help': 'Cari bantuan...',
      'still_need_help': 'Masih butuh bantuan?',
      'team_ready': 'Tim kami siap membantu Anda 24/7.',
      'faq_1_q': 'Bagaimana cara kerja Jurnal AI?',
      'faq_1_a': 'Jurnal AI menggunakan teknologi pemrosesan bahasa alami untuk menganalisis emosi dalam tulisan Anda dan memberikan saran yang relevan.',
      'faq_2_q': 'Apakah data saya aman?',
      'faq_2_a': 'Sangat aman. Semua jurnal Anda disimpan secara lokal dan tidak dapat diakses oleh siapa pun tanpa izin Anda.',
      'faq_3_q': 'Bagaimana cara mengganti tema?',
      'faq_3_a': 'Anda dapat mengganti tema di halaman Profil melalui tombol toggle "Mode Gelap".',
      'faq_4_q': 'Apakah aplikasi ini gratis?',
      'faq_4_a': 'Ya, fitur utama RuangTenang tersedia secara gratis untuk membantu kesehatan mental Anda.',
      'faq_5_q': 'Bagaimana cara mengganti bahasa?',
      'faq_5_a': 'Anda dapat mengganti bahasa di halaman Profil melalui menu "Bahasa". Kami mendukung Bahasa Indonesia dan Inggris.',
      'follow_us': 'Ikuti Kami',
      'our_mission_desc': 'RuangTenang hadir sebagai sahabat digital untuk kesehatan mental Anda. Kami percaya bahwa setiap orang berhak memiliki ruang aman untuk bercerita dan menemukan kedamaian di tengah kesibukan dunia.',
      'feature_1_title': 'Jurnal AI',
      'feature_1_desc': 'Analisis perasaan yang cerdas.',
      'feature_2_title': 'Relaksasi',
      'feature_2_desc': 'Audio penenang untuk meditasi.',
      'feature_3_title': 'Statistik Mood',
      'feature_3_desc': 'Pantau perkembangan emosi Anda.',
      'developed_by': 'Dikembangkan dengan penuh ❤️ oleh Tim RuangTenang.',
      'version': 'Versi',
      'our_mission': 'Misi Kami',
      'main_features': 'Fitur Utama',
      'contribution': 'Kontribusi',
      // Journal Page
      'journal_title': 'Jurnal Harian',
      'how_feel_journal': 'Bagaimana\nperasaanmu hari ini?',
      'journal_hint': 'Tidak ada jawaban yang salah. Ceritakan dengan jujur.',
      'write_feeling': 'Tulis Perasaanmu',
      'write_feeling_desc': 'Ceritakan apa saja yang ada di pikiranmu',
      'journal_input_hint': 'Hari ini aku merasa...',
      'eval_condition': 'EVALUASI KONDISI',
      'eval_desc': 'Pilih seberapa sering kamu merasakan hal-hal\nberikut dalam 2 minggu terakhir.',
      'total_score_phq9': 'Total Skor PHQ-9',
      'analyze_now': 'Analisis Sekarang',
      'scale_0': 'Tidak pernah',
      'scale_1': 'Beberapa hari',
      'scale_2': 'Lebih dari seminggu',
      'scale_3': 'Hampir setiap hari',
      'q1_title': 'Perasaan Sedih',
      'q1_desc': 'Merasa sedih, murung, atau tidak punya harapan',
      'q2_title': 'Minat & Kegiatan',
      'q2_desc': 'Kurang tertarik atau tidak menikmati aktivitas seperti biasa',
      'q3_title': 'Kualitas Tidur',
      'q3_desc': 'Sulit tidur, terlalu banyak tidur, atau tidur tidak nyenyak',
      'q4_title': 'Tingkat Kelelahan',
      'q4_desc': 'Merasa lelah atau tidak punya energi untuk beraktivitas',
      'q5_title': 'Konsentrasi',
      'q5_desc': 'Sulit fokus saat membaca, menonton, atau melakukan pekerjaan',
      // Chat Page
      'chat_title': 'RuangTenang AI',
      'chat_welcome': 'Halo, apa yang sedang mengganggu pikiranmu hari ini? Ceritakan saja, aku siap mendengarkan.',
      'chat_typing': 'RuangTenang sedang mengetik',
      'chat_hint': 'Ketik pesan...',
      'chat_error_conn': 'Gagal terhubung ke server. Pastikan backend jalan.',
      'chat_error_detail': 'Error koneksi: Pastikan Backend Laravel sudah di-serve dan URL API sudah benar.',
      'chat_error_empty': 'Maaf, tidak ada balasan dari AI.',
      'analyze_my_condition': 'Analisis Kondisiku',
      'no_recent_journal': 'Belum ada jurnal. Yuk mulai menulis! ✍️',
      'how_feel_now': 'Bagaimana perasaanmu saat ini?',
      'mood_saved_snack': 'Mood tersimpan! Yuk lanjut ceritakan perasaanmu lebih dalam di Jurnal AI 📝',
      'mood_v_sad': 'Sangat Sedih',
      'mood_sad': 'Sedih',
      'mood_neutral': 'Netral',
      'mood_happy': 'Senang',
      'mood_v_happy': 'Sangat Senang',
      'recommended_articles': 'Artikel Rekomendasi',
      // Journal Results
      'res_minimal_title': 'Kondisi Minimal',
      'res_minimal_desc': 'Kondisi mentalmu cukup baik saat ini. Teruslah menjaga keseimbangan dan luangkan waktu untuk merawat diri.',
      'res_minimal_cta': 'Bagus sekali! Tetap jaga ya 💚',
      'res_ringan_title': 'Gejala Ringan',
      'res_ringan_desc': 'Ada sedikit tekanan yang kamu rasakan. Istirahat yang cukup dan olahraga ringan dapat sangat membantu.',
      'res_ringan_cta': 'Kamu tidak sendiri 💛',
      'res_sedang_title': 'Gejala Sedang',
      'res_sedang_desc': 'Kamu mungkin membutuhkan dukungan lebih. Pertimbangkan untuk berbicara dengan konselor atau psikolog.',
      'res_sedang_cta': 'Minta bantuan adalah kekuatan 🧡',
      'res_berat_title': 'Gejala Berat',
      'res_berat_desc': 'Kondisimu membutuhkan perhatian serius. Jangan ragu untuk segera menghubungi psikolog atau psikiater terdekat.',
      'res_berat_cta': 'Segera cari bantuan profesional ❤️',
      'close': 'Tutup',
      'score': 'Skor',
      'chat_trigger_title': 'Cek Kondisi Mentalmu',
      'chat_trigger_sub': 'Sudah beberapa saat kita ngobrol',
      'chat_trigger_desc': 'Yuk, lakukan pengecekan kondisi mental lebih mendalam dengan Jurnal AI. Hanya 2 menit, dan kamu akan mendapatkan analisis serta rekomendasi yang lebih personal. 💜',
      'chat_trigger_cta': 'Mulai Cek Kondisi Mental',
      'chat_articles_label': 'Artikel untukmu',
      // Article Recommendations
      'art_stres_1_t': 'Teknik Napas 4-7-8',
      'art_stres_1_s': 'Redakan stres dalam 1 menit',
      'art_stres_2_t': 'Jalan Kaki & Stres',
      'art_stres_2_s': 'Olahraga ringan yang ampuh',
      'art_stres_3_t': 'Journaling untuk Stres',
      'art_stres_3_s': 'Tulis, lepaskan, lega',
      'art_cemas_1_t': 'Mindfulness 5 Menit',
      'art_cemas_1_s': 'Hadirkan dirimu saat ini',
      'art_cemas_2_t': 'Musik & Kecemasan',
      'art_cemas_2_s': 'Playlist yang menenangkan jiwa',
      'art_cemas_3_t': 'Kelola Energi Mental',
      'art_cemas_3_s': 'Jaga batas agar tidak overwhelmed',
      'art_sedih_1_t': 'Validasi Perasaanmu',
      'art_sedih_1_s': 'Boleh sedih, itu manusiawi',
      'art_sedih_2_t': 'Cerita ke Orang Terdekat',
      'art_sedih_2_s': 'Kamu tidak harus sendiri',
      'art_sedih_3_t': 'Rutinitas Penyembuh',
      'art_sedih_3_s': 'Kebiasaan kecil yang membantu',
      'art_lelah_1_t': 'Pentingnya Tidur Cukup',
      'art_lelah_1_s': 'Otak butuh rehat yang berkualitas',
      'art_lelah_2_t': 'Istirahat Aktif',
      'art_lelah_2_s': 'Bukan rebahan, tapi recharge',
      'art_lelah_3_t': 'Self-Care Sederhana',
      'art_lelah_3_s': 'Me-time yang efektif',
      'art_marah_1_t': 'Kelola Amarah dengan Sehat',
      'art_marah_1_s': 'Emosi valid, ekspresi bisa dipilih',
      'art_marah_2_t': 'Teknik Grounding',
      'art_marah_2_s': 'Kembali tenang dalam 5 langkah',
      'art_marah_3_t': 'Ekspresikan lewat Tulisan',
      'art_marah_3_s': 'Tuangkan ke kertas, bukan orang',
      'art_burnout_1_t': 'Kenali Tanda Burnout',
      'art_burnout_1_s': 'Sebelum terlambat, sadari sekarang',
      'art_burnout_2_t': 'Digital Detox',
      'art_burnout_2_s': 'Istirahat dari layar secara berkala',
      'art_burnout_3_t': 'Cari Bantuan Profesional',
      'art_burnout_3_s': 'Psikolog bisa membantumu pulih',
      'art_default_1_t': 'Menjaga Kesehatan Mental',
      'art_default_1_s': 'Panduan dasar untuk setiap hari',
      'art_default_2_t': 'Tumbuh dari Tantangan',
      'art_default_2_s': 'Resiliensi yang bisa dipelajari',
      'art_default_3_t': 'Mulai Hari dengan Positif',
      'art_default_3_s': 'Rutinitas pagi yang menyehatkan',
      // Notifications
      'notif_title_1': 'Waktunya Menulis Jurnal ✍️',
      'notif_body_1': 'Bagaimana harimu? Ceritakan di RuangTenang yuk!',
      'notif_title_2': 'Rehat Sejenak 🌿',
      'notif_body_2': 'Sudahkah kamu bernapas lega hari ini? Mari tuangkan pikiranmu sebentar...',
      'notif_title_3': 'Momen Refleksi 📖',
      'notif_body_3': 'Ada hal menarik apa hari ini? Tuliskan agar tidak terlupakan.',
      'notif_title_4': 'Ruang Amanmu 💜',
      'notif_body_4': 'Halo! Bagaimana perasaanmu saat ini? Aku siap mendengarkan.',
      'notif_title_5': 'Ceritakan Harimu ✨',
      'notif_body_5': 'Jangan biarkan pikiranmu penuh, lepaskan semuanya di sini ya.',
    },
    'en': {
      'app_title': 'RuangTenang',
      'welcome': 'Welcome back',
      'how_feel': 'How are you feeling today?',
      'start_journal': 'Start New Journal',
      'journal_desc': 'Share your heart today to make your mind calmer.',
      'chat_now': 'Chat\nNow',
      'recent_journal': 'Recent Journals',
      'see_all': 'See All →',
      'stats_mood': 'Mood Statistics',
      'total_journal': 'Total Journals',
      'dominant_mood': 'Dominant Mood',
      'relax_session': 'Relaxation Sessions',
      'profile_title': 'Profile & Settings',
      'app_settings': 'App Settings',
      'dark_mode': 'Dark Mode',
      'notif': 'Notifications',
      'lang': 'Language',
      'privacy': 'Privacy & Security',
      'help_info': 'Help & Info',
      'help_center': 'Help Center',
      'about_app': 'About App',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'edit_profile': 'Edit Profile',
      'save': 'Save',
      'health_mental': 'Mental Health Education',
      'health_desc': 'Learn meditation techniques, stress management, and more.',
      'edu_center': 'Education Center',
      'all_articles': 'All Articles →',
      'tab_home': 'Home',
      'tab_journal': 'Journal',
      'tab_chat': 'Chat',
      'tab_profile': 'Profile',
      'dash_no_data': 'No mood data today',
      'dash_error': 'Failed to load mood data',
      'send_test_notif': 'Send Test Notification',
      'privacy_title': 'Privacy & Security',
      'account_security': 'Account Security',
      'data_encryption': 'Data Encryption',
      'data_encryption_desc': 'All your journals and mood data are encrypted locally on your device.',
      'biometric': 'Biometric Security',
      'biometric_desc': 'Fingerprint or face lock options are coming soon.',
      'data_privacy': 'Data Privacy',
      'anon_data': 'Anonymous Data',
      'anon_data_desc': 'We do not share your personal identity with any third parties.',
      'delete_data': 'Delete All Data',
      'delete_data_desc': 'You can delete your entire journal history at any time through account settings.',
      'legal': 'Legal',
      'tos': 'Terms & Conditions',
      'tos_content': '1. Use of Service\nBy using RuangTenang, you agree to use this application for personal mental health purposes and not to abuse our AI system.\n\n2. Limitation of Liability\nThis service is an AI-based support assistant and not a substitute for professional medical consultation, psychologist, or psychiatrist.\n\n3. User Account\nYou are responsible for maintaining the confidentiality of your account and login data.',
      'privacy_policy': 'Privacy Policy',
      'privacy_content': '1. Data Collection\nWe store your journal texts and mood analysis results to provide a history of your mental health progress.\n\n2. Data Security\nYour data is stored with encryption and will not be shared with third parties without your permission.\n\n3. User Rights\nYou have full rights to delete your entire data history at any time through the "Delete All Data" feature in this application.',
      'faq_popular': 'Popular Questions',
      'contact_us': 'Contact Us',
      'search_help': 'Search for help...',
      'still_need_help': 'Still need help?',
      'team_ready': 'Our team is ready to help you 24/7.',
      'faq_1_q': 'How does AI Journal work?',
      'faq_1_a': 'AI Journal uses natural language processing technology to analyze emotions in your writing and provide relevant suggestions.',
      'faq_2_q': 'Is my data safe?',
      'faq_2_a': 'Very safe. All your journals are stored locally and cannot be accessed by anyone without your permission.',
      'faq_3_q': 'How do I change the theme?',
      'faq_3_a': 'You can change the theme on the Profile page via the "Dark Mode" toggle button.',
      'faq_4_q': 'Is this app free?',
      'faq_4_a': 'Yes, the main features of RuangTenang are available for free to help your mental health.',
      'faq_5_q': 'How to change the language?',
      'faq_5_a': 'You can change the language on the Profile page via the "Language" menu. We support Indonesian and English.',
      'follow_us': 'Follow Us',
      'our_mission_desc': 'RuangTenang comes as a digital companion for your mental health. We believe that everyone deserves to have a safe space to share stories and find peace amidst the bustle of the world.',
      'feature_1_title': 'AI Journal',
      'feature_1_desc': 'Smart feeling analysis.',
      'feature_2_title': 'Relaxation',
      'feature_2_desc': 'Soothing audio for meditation.',
      'feature_3_title': 'Mood Statistics',
      'feature_3_desc': 'Monitor your emotional development.',
      'developed_by': 'Developed with ❤️ by the RuangTenang Team.',
      'version': 'Version',
      'our_mission': 'Our Mission',
      'main_features': 'Main Features',
      'contribution': 'Contribution',
      // Journal Page
      'journal_title': 'Daily Journal',
      'how_feel_journal': 'How are you\nfeeling today?',
      'journal_hint': 'There are no wrong answers. Tell it honestly.',
      'write_feeling': 'Write Your Feelings',
      'write_feeling_desc': 'Tell me anything that is on your mind',
      'journal_input_hint': 'Today I feel like...',
      'eval_condition': 'CONDITION EVALUATION',
      'eval_desc': 'Choose how often you have felt the following things in the last 2 weeks.',
      'total_score_phq9': 'Total PHQ-9 Score',
      'analyze_now': 'Analyze Now',
      'scale_0': 'Not at all',
      'scale_1': 'Several days',
      'scale_2': 'More than half the days',
      'scale_3': 'Nearly every day',
      'q1_title': 'Feeling Sad',
      'q1_desc': 'Feeling down, depressed, or hopeless',
      'q2_title': 'Interest & Activities',
      'q2_desc': 'Little interest or pleasure in doing things',
      'q3_title': 'Sleep Quality',
      'q3_desc': 'Trouble falling or staying asleep, or sleeping too much',
      'q4_title': 'Energy Levels',
      'q4_desc': 'Feeling tired or having little energy',
      'q5_title': 'Concentration',
      'q5_desc': 'Trouble concentrating on things, such as reading or watching TV',
      // Chat Page
      'chat_title': 'RuangTenang AI',
      'chat_welcome': 'Hello, what\'s on your mind today? Just tell me, I\'m ready to listen.',
      'chat_typing': 'RuangTenang is typing',
      'chat_hint': 'Type a message...',
      'chat_error_conn': 'Failed to connect to server. Make sure backend is running.',
      'chat_error_detail': 'Connection error: Make sure Backend Laravel is served and API URL is correct.',
      'chat_error_empty': 'Sorry, there is no reply from the AI.',
      'analyze_my_condition': 'Analyze My Condition',
      'no_recent_journal': 'No journals yet. Let\'s start writing! ✍️',
      'how_feel_now': 'How are you feeling right now?',
      'mood_saved_snack': 'Mood saved! Let\'s pour your feelings out more in AI Journal 📝',
      'mood_v_sad': 'Very Sad',
      'mood_sad': 'Sad',
      'mood_neutral': 'Neutral',
      'mood_happy': 'Happy',
      'mood_v_happy': 'Very Happy',
      'recommended_articles': 'Recommended Articles',
      // Journal Results
      'res_minimal_title': 'Minimal Symptoms',
      'res_minimal_desc': 'Your mental condition is quite good at the moment. Continue to maintain balance and take time for self-care.',
      'res_minimal_cta': 'Great! Keep it up 💚',
      'res_ringan_title': 'Mild Symptoms',
      'res_ringan_desc': 'You\'re feeling a bit of pressure. Getting enough rest and light exercise can help a lot.',
      'res_ringan_cta': 'You are not alone 💛',
      'res_sedang_title': 'Moderate Symptoms',
      'res_sedang_desc': 'You might need more support. Consider talking to a counselor or psychologist.',
      'res_sedang_cta': 'Asking for help is a strength 🧡',
      'res_berat_title': 'Severe Symptoms',
      'res_berat_desc': 'Your condition requires serious attention. Don\'t hesitate to immediately contact the nearest psychologist or psychiatrist.',
      'res_berat_cta': 'Seek professional help immediately ❤️',
      'close': 'Close',
      'score': 'Score',
      'chat_trigger_title': 'Check Your Mental Condition',
      'chat_trigger_sub': 'We\'ve been chatting for a while',
      'chat_trigger_desc': 'Come on, do a more in-depth mental condition check with AI Journal. It only takes 2 minutes, and you\'ll get more personal analysis and recommendations. 💜',
      'chat_trigger_cta': 'Start Mental Condition Check',
      'chat_articles_label': 'Articles for you',
      // Article Recommendations
      'art_stres_1_t': '4-7-8 Breathing Technique',
      'art_stres_1_s': 'Relieve stress in 1 minute',
      'art_stres_2_t': 'Walking & Stress',
      'art_stres_2_s': 'Powerful light exercise',
      'art_stres_3_t': 'Journaling for Stress',
      'art_stres_3_s': 'Write, release, relief',
      'art_cemas_1_t': '5-Minute Mindfulness',
      'art_cemas_1_s': 'Be present in the moment',
      'art_cemas_2_t': 'Music & Anxiety',
      'art_cemas_2_s': 'Soul-soothing playlists',
      'art_cemas_3_t': 'Manage Mental Energy',
      'art_cemas_3_s': 'Keep boundaries to avoid overwhelm',
      'art_sedih_1_t': 'Validate Your Feelings',
      'art_sedih_1_s': 'It\'s okay to be sad, it\'s human',
      'art_sedih_2_t': 'Talk to Someone Close',
      'art_sedih_2_s': 'You don\'t have to be alone',
      'art_sedih_3_t': 'Healing Routines',
      'art_sedih_3_s': 'Small habits that help',
      'art_lelah_1_t': 'Importance of Enough Sleep',
      'art_lelah_1_s': 'The brain needs quality rest',
      'art_lelah_2_t': 'Active Rest',
      'art_lelah_2_s': 'Not lying down, but recharging',
      'art_lelah_3_t': 'Simple Self-Care',
      'art_lelah_3_s': 'Effective me-time',
      'art_marah_1_t': 'Manage Anger Healthily',
      'art_marah_1_s': 'Valid emotions, choice of expression',
      'art_marah_2_t': 'Grounding Techniques',
      'art_marah_2_s': 'Get calm in 5 steps',
      'art_marah_3_t': 'Express via Writing',
      'art_marah_3_s': 'Pour it onto paper, not people',
      'art_burnout_1_t': 'Recognize Burnout Signs',
      'art_burnout_1_s': 'Before it\'s too late, realize now',
      'art_burnout_2_t': 'Digital Detox',
      'art_burnout_2_s': 'Break from screens regularly',
      'art_burnout_3_t': 'Seek Professional Help',
      'art_burnout_3_s': 'Psychologists can help you recover',
      'art_default_1_t': 'Maintaining Mental Health',
      'art_default_1_s': 'Basic guide for every day',
      'art_default_2_t': 'Growing from Challenges',
      'art_default_2_s': 'Resilience can be learned',
      'art_default_3_t': 'Start Day Positively',
      'art_default_3_s': 'Healthy morning routines',
      // Notifications
      'notif_title_1': 'Time to Journal ✍️',
      'notif_body_1': 'How was your day? Let\'s share it in RuangTenang!',
      'notif_title_2': 'Take a Break 🌿',
      'notif_body_2': 'Have you taken a deep breath today? Let\'s pour your thoughts...',
      'notif_title_3': 'Reflection Moment 📖',
      'notif_body_3': 'Anything interesting today? Write it down so you won\'t forget.',
      'notif_title_4': 'Your Safe Space 💜',
      'notif_body_4': 'Hello! How are you feeling right now? I\'m ready to listen.',
      'notif_title_5': 'Tell Your Story ✨',
      'notif_body_5': 'Don\'t let your mind be full, release it all here.',
    },
  };
}
